### ISSUE TITLE
Missing Repository for activisthub.org

### ISSUE THREAD

**Issue by benjosua** [veganhacktivists/arabot#125]
Is there a way to contribute ideas and code to https://activisthub.org/ and https://cubeoftruth.com/ ?

**Comment by smyalygames** [comment]
Hiya, this repository is for a Discord bot for ARA, and I only manage ARA related stuff.

I would take a look at https://veganhacktivists.org/join if you want to potentially contribute, or sending an email asking further about this. You can find the email at the bottom of the page I linked.
