### ISSUE TITLE
Add a captcha for new users

### ISSUE THREAD

**Issue by smyalygames** [veganhacktivists/arabot#56]
**Is your feature request related to a problem? Please describe.**
To prevent bots from flooding the server

**Describe the solution you'd like**
When a user joins and agrees to the rules, they should be prompted to complete a captcha

**Describe alternatives you've considered**
Only requiring the user to agree to the rules, which would most likely need manual input from a user

**Comment by Leftyxiv** [comment]
Are you ok with adding more external dependencies?  I know it can add to tech debt but this looks like it may be useful for this

https://www.npmjs.com/package/discord.js-captcha

**Comment by smyalygames** [comment]
> Are you ok with adding more external dependencies? I know it can add to tech debt but this looks like it may be useful for this
> 
> https://www.npmjs.com/package/discord.js-captcha

This looks awesome! :D

I think this is something that may be added after we implement the verification system #35 and I could discuss how this should be done.
