### ISSUE TITLE
Sus Command: Purged notes persist in database

### ISSUE THREAD

**Issue by maross3** [veganhacktivists/arabot#69]
**Describe the bug**
Sus command does not remove entries from database when removed from a user. 

**To Reproduce**
1. type `/sus add @name test`
2. type `/sus purge @name`
3. The entries are still located in the database

**Expected behavior**
Purged notes should be removed from the database

**Comment by Leftyxiv** [comment]
I don't have permissions to try this on the live server but I had no problems in the test server.  might be an environment issue?
![sus](https://user-images.githubusercontent.com/55634405/205410647-4fa87754-9296-47c1-a315-fc630b823ecc.png)
